services:
  gotosocial:
    image: superseriousbusiness/gotosocial:latest
    container_name: gotosocial
    restart: unless-stopped
    entrypoint:
      [
        "/gotosocial/gotosocial",
        "server",
        "start",
        "--config-path",
        "/gotosocial/config.yaml",
      ]
    environment:
      - TZ=Europe/Prague
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./data:/gotosocial/storage
      - ./config/config.yaml:/gotosocial/config.yaml
    user: "1000:1000"
