server {
    listen 80;
    listen [::]:80;
    server_name ACCOUNT_DOMAIN;

    # Webfinger a discovery endpointy – přesměruj na GoToSocial instanci
    location = /.well-known/webfinger {
        return 301 https://GTS_HOST$request_uri;
    }

    location = /.well-known/nodeinfo {
        return 301 https://GTS_HOST$request_uri;
    }

    location = /.well-known/host-meta {
        return 301 https://GTS_HOST$request_uri;
    }
}
